package api.sockets;

/**
 * Created by szpt_user045 on 11.07.2019.
 */
public enum Subscriber {
    DEAL_BUY,
    DEAL_BUY_ARCHIVE,
    DEAL_SELL,
    DEAL_SELL_ARCHIVE,
    LOAD_PLAN,
    LOAD_PLAN_ARCHIVE,
    LOGISTIC,
    LOGISTIC_ARCHIVE,
    TRANSPORT_BUY,
    TRANSPORT_BUY_ARCHIVE,
    TRANSPORT_SELL,
    TRANSPORT_SELL_ARCHIVE,
    PROBES,
    EXTRACTION,
    LABORATORY_TURNS,
    VRO,
    KPO,
    LABORATORY_STORAGES,
    LABORATORY_BUY,
    LABORATORY_BUY_ARCHIVE,
    LABORATORY_SELL,
    LABORATORY_SELL_ARCHIVE,
    MESSAGES,
    MANUFACTURE_REPORTS,
    USERS,
    STOCK,
    FINAL_STOCK,
    SESSION_TIMER,
    CONTRACTS_BUY,
    CONTRACTS_SELL,
    TRANSPORT,
    TRANSPORT_ARCHIVE
}

//10592