INSERT INTO public.document_organisations VALUES (1, TRUE, 'СЗПТ');
INSERT INTO public.document_organisations VALUES (2, TRUE, 'ПП Млин');
INSERT INTO public.organisations VALUES (DEFAULT , 'Сумський ЗПТ', 'ПрАТ');
INSERT INTO public.products VALUES (DEFAULT, 'sun', 'Насіння Соняшника', NULL);
INSERT INTO public.products VALUES (DEFAULT, 'oil', 'Олія нерафінована', NULL);
INSERT INTO public.products VALUES (DEFAULT, 'oil', 'Олія рафінована', NULL);
INSERT INTO public.products VALUES (DEFAULT, 'cake', 'Макуха соняшникова', NULL);
INSERT INTO public.products VALUES (DEFAULT, 'meal', 'Шрот', NULL);
INSERT INTO public.storages VALUES (DEFAULT, 'Склад Шроту');
INSERT INTO public.storages VALUES (DEFAULT, 'Ємність 150 м2 №1');
INSERT INTO public.storages VALUES (DEFAULT, 'Ємність 150 м2 №2');
INSERT INTO public.storages VALUES (DEFAULT, 'Ємність 150 м3 №3');
INSERT INTO public.storages VALUES (DEFAULT, 'Свічка №1');
INSERT INTO public.storages VALUES (DEFAULT, 'Свічка №2');
INSERT INTO public.storages VALUES (DEFAULT, 'Свічка №3');
INSERT INTO public.storage_product VALUES (DEFAULT, 1, 5);
INSERT INTO public.storage_product VALUES (DEFAULT, 2, 2);
INSERT INTO public.storage_product VALUES (DEFAULT, 3, 2);
INSERT INTO public.storage_product VALUES (DEFAULT, 4, 2);
INSERT INTO public.storage_product VALUES (DEFAULT, 5, 2);
INSERT INTO public.storage_product VALUES (DEFAULT, 6, 2);
INSERT INTO public.storage_product VALUES (DEFAULT, 7, 2);
INSERT INTO public.subdivisions VALUES(1, 'ex', 'Екстракція');
INSERT INTO public.subdivisions VALUES(2, 'vro', 'ВРО');
INSERT INTO public.subdivisions VALUES(3, 'kpo', 'КПО');
INSERT INTO public.turn_settings VALUES(1, '08:00:00', '20:00:00', 1);
INSERT INTO public.turn_settings VALUES(2, '20:00:00', '08:00:00', 2);
INSERT INTO public.app_settings VALUES(1, 'szpt', 1);
INSERT INTO public.weight_units VALUES (1, 'т.');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ПП');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ТОВ');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ПАТ');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ПРАТ');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ФОП');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ФГ');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'СФГ');
INSERT INTO public.organisation_types VALUES (DEFAULT, 'ПСП');
INSERT INTO public.forpress VALUES (1, 'Ф-300');
INSERT INTO public.forpress VALUES (2, 'Ф-100');
